[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form settings
[functions]
  directory = "netlify/functions"

# Environment variables (set these in Netlify dashboard)