backend:
  name: github
  repo: Habakuk0/FinExactSolutions   # ✅ Your GitHub repo
  branch: main                       # branch to publish changes

site_url: https://finexactsolutions.co.ke

media_folder: "client/src/assets/uploads"   # ✅ Actual folder for uploaded media
public_folder: "/src/assets/uploads"        # URL path used in markdown/images

publish_mode: editorial_workflow            # Keeps drafts until published

collections:
  - name: "resources"                        # Name used in CMS API
    label: "Resources"                        # Label shown in CMS UI
    folder: "client/src/content/resources"    # ✅ Correct folder where markdown is stored
    create: true                              # Allow new files
    slug: "{{slug}}"                          # File name pattern
    preview_path: "resources/{{slug}}"        # Live preview path
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", default: "{{title | slug}}" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }    # ✅ use "image" widget for uploads
      - { label: "Body", name: "body", widget: "markdown" }
