backend:
  name: github
  repo: Habakuk0/finexactsite   # your GitHub repo
  branch: main                  # branch for content
  base_url: https://api.netlify.com
  auth_endpoint: /.netlify/identity

site_url: https://www.finexactsolutions.co.ke

media_folder: "client/src/assets/uploads"
public_folder: "/src/assets/uploads"

publish_mode: editorial_workflow

collections:
  - name: "resources"
    label: "Resources"
    folder: "client/src/content/resources"
    create: true
    slug: "{{slug}}"
    preview_path: "resources/{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string", default: "{{title | slug}}" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }

